spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ev_music?useSSL=false

#    hikari:
#      connection-timeout: 250
#      0.1 sec -> Test Only
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

# MyBatis
#mybatis:
#  mapper-locations: mapper/**/*.xml

## Monitoring: Actuator(Spring To Prometheus)
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus
#
