spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ev_music?useSSL=false

# MyBatis
mybatis:
  mapper-locations: mapper/**/*.xml
